### ISSUE TITLE
Type stability issue in Julia 1.0

### ISSUE THREAD

**Issue by MaximeBouton** [JuliaPOMDP/RLInterface.jl#25]
The tests that we have for type stability are breaking in julia 1.0 when I wrap the `gen` function into another function. I don't know why, any help would be appreciated, here is a MWE:

```julia
using POMDPs, POMDPModels, Random, Test

mdp = SimpleGridWorld()
rng = MersenneTwister(1)
s = initialstate(mdp, rng)
a = :up

@inferred gen(DDNOut(:sp, :r), mdp, s, a, rng) # This is fine

struct MDPEnv{M, S, R}
    prob::M
    s::S
    rng::R
end

function step(env::MDPEnv, a)
    return gen(DDNOut(:sp, :r), env.prob, env.s, a, env.rng)
end

env = MDPEnv(mdp, s, rng)

@inferred step(env, a) # This errors

@code_warntype step(env, a)
```

Tests on julia 1.2 are passing.

@zsunberg, @lassepe any ideas?

**Comment by lassepe** [comment]
We noticed a [similar issue](https://github.com/JuliaPOMDP/POMCPOW.jl/issues/12) in POMCPOW and BasicPOMCP as well. There we decided to not support 1.0.x for the new release. Interestingly, this is a problem only in 1.0.x. In 0.7 it's fine and starting from 1.1.x it is also not a problem.

The main issue here seems to be that `DDNOut(:sp, :r)` is not recognized as a compile time constant. You can make it work in Julia 1.0 by constructing the DDNOut value type explicitly:

```julia
function step(env::MDPEnv, a)
    return gen(DDNOut{(:sp, :r)}(), env.prob, env.s, a, env.rng)
end
```

Maybe an `@inline` or `@pure` annotation at the `DDNOut` method definition might help the 1.0 compiler, @zsunberg ?

By the way: this is exactly the reason why I [keep asking for a julia equivalent of the C++ constexpr](https://stackoverflow.com/questions/57567406/in-julia-is-there-a-macro-to-determine-whether-an-expression-can-be-evaluated-a) because I am not very convinced by the "hopefully the compiler will figure out" answer.

**Comment by lassepe** [comment]
@MaximeBouton did the fix in https://github.com/JuliaPOMDP/POMDPs.jl/pull/270/commits/db4a655a0efe33cd5dbfa4d2775800e18c21d812 fix this issue for you? I've noticed that it fixed the bug for your MWE but the problem that we saw in BasicPOMCP and POMCPOW seems not to be fixed by this.

**Comment by MaximeBouton** [comment]
Yes it seems to work! Thanks!
