### ISSUE TITLE
Register package with General

### ISSUE THREAD

**Issue by mossr** [JuliaPOMDP/RLInterface.jl#35]
As many of the JuliaPOMDP solver have already, I think it's time to register `RLInterface` with the General registry.

**Comment by MaximeBouton** [comment]
yeah I am wondering if we need to change the name though :/ 
Any thoughts? 
The future is to rely on CommonRLInterface.jl I believe but there is still some work to be done.

**Comment by mossr** [comment]
I'm curious how many projects are dependent on `RLInterface`, thus a name change before migrating to `CommonRLInterface` in the future might be an unnecessary headache.

I tried to come up with "POMDPs" style naming, but it got messy real fast: `POMDPRLInterface`, `POMDPReinforcementInterface`, `POMDPReinforcementLearningInterface`, `PartiallyObservableMarkovDecisionProcessReinforcementLearningInterface` (kidding, of course...)

**Comment by MaximeBouton** [comment]
I only know of DeepQLearning, are the new repos with CEM and policy optimization depending on it? 
If it is only DeepQLearning, I can try to add RLInterface as a submodule or try to make it not depend on it. The main advantage is that it made it easy to have the same DQN implementation regardless of whether the problem is an MDP or a POMDP.

**Comment by mossr** [comment]
`POMDPStressTesting` depends on it (the `PolicyOptimization` submodule uses it, which eventually will be spun out to its own package).

**Comment by mossr** [comment]
We can close this as `POMDPStressTesting` has moved to use `CommonRLInterface` instead.
